# 定义一个新程序，名字叫 docker-node-hello
[program:docker-node-hello]
# 工作目录切换到 /data/app
directory=/data/app
# 用绝对路径启动 Node，执行 index.js
command=/usr/local/bin/node /data/app/index.js
# 标准输出日志存到哪里（%(program_name)s 会被替换成 docker-node-hello）
stdout_logfile=/var/log/supervisor/%(program_name)s.log
# 错误日志存到哪里
stderr_logfile=/var/log/supervisor/%(program_name)s.log
# 程序挂了自动重启
autorestart=true